@URL = https://vttiike0hl.execute-api.ap-southeast-1.amazonaws.com/


### Get all users
GET {{URL}}/users

### Create a user
POST {{URL}}/users
Content-Type: application/json

{
    "name": "coding addict"
}

### Get a user
GET {{URL}}/users/b7d7af70-b537-41cf-93d7-08e1e9b56a46

### Update a user
PUT {{URL}}/users/b7d7af70-b537-41cf-93d7-08e1e9b56a46
Content-Type: application/json

{
    "name": "coding addict",
    "email": "coding@addict.com"
}

### Delete a user
DELETE {{URL}}/users/b7d7af70-b537-41cf-93d7-08e1e9b56a46
